### ISSUE TITLE
Missing in package control list

### ISSUE THREAD

**Issue by codemakerlive** [mogga/sublime-nunjucks#4]
Hi, 

I'm unable to locate this package when installing via Package Control. Further your package control website page has a "MISSING" indicator beneath the package title. Incorrect download URL?

Thanks,

**Comment by jdahdah** [comment]
PackageControl.io still links to https://github.com/mogga/sublime-nunjucks. Although Github redirects to https://github.com/robmoggach/sublime-nunjucks, PackageControl doesn't follow the redirect. I think only @robmoggach can fix this?

**Comment by rjmoggach** [comment]
argh... let me know how to fix and i'll fix it

## 

Robert Moggach
Sr. VFX Supervisor / Flame Artist
Los Angeles / New York / London / Toronto
http://moggach.com
https://www.linkedin.com/profile/view?id=1664843
Mobile (310) 773-1793

**Comment by alaimo** [comment]
Any update.  I would love to try this out.  I think you will need to submit a pull request to https://github.com/wbond/package_control_channel to fix this.

**Comment by rjmoggach** [comment]
transferred to @mogga from @robmoggach - let me know if it's working now
